#pragma once

#ifndef OSCI_PREMIUM
#define OSCI_PREMIUM 0
#endif

#ifndef OSCI_PROPRIETARY_BUILD
#define OSCI_PROPRIETARY_BUILD 0
#endif

#ifndef OSCI_RENDER_CORE_ENABLE_MIDI_CC_LEARN
#define OSCI_RENDER_CORE_ENABLE_MIDI_CC_LEARN OSCI_PREMIUM
#endif
