#pragma once

#ifndef OSCI_PROPRIETARY_BUILD
#define OSCI_PROPRIETARY_BUILD 0
#endif

#ifndef OSCI_RENDER_CORE_ENABLE_CHOWDSP_RESAMPLING
#define OSCI_RENDER_CORE_ENABLE_CHOWDSP_RESAMPLING 0
#endif

#if OSCI_PROPRIETARY_BUILD && OSCI_RENDER_CORE_ENABLE_CHOWDSP_RESAMPLING
#error "OSCI_RENDER_CORE_ENABLE_CHOWDSP_RESAMPLING cannot be enabled in OSCI_PROPRIETARY_BUILD."
#endif
